In [1]:
import numpy as np

C:\Users\yTonomura\anaconda3\envs\AI\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\yTonomura\anaconda3\envs\AI\lib\site-packages\numpy\.libs\libopenblas.GK7GX5KEQ4F6UYO3P26ULGBQYHGQO7J4.gfortran-win_amd64.dll
C:\Users\yTonomura\anaconda3\envs\AI\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array(range(1,4))

array([1, 2, 3])

In [6]:
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
A.shape

(2, 3)

In [8]:
A.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
A.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
A.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
B = A.reshape(3,2)
np.append(B, [[7,8]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
np.append(B, [[7], [8], [9]], axis=1)

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [13]:
B[0]

array([1, 2])

In [14]:
B[0][1]

2

In [15]:
B+2

array([[3, 4],
       [5, 6],
       [7, 8]])

In [16]:
B*3

array([[ 3,  6],
       [ 9, 12],
       [15, 18]])

In [17]:
A, B

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [18]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [20]:
# uniform distribution between 0 to 1
np.random.rand(3,2)

array([[0.12659027, 0.79623453],
       [0.97093473, 0.7609181 ],
       [0.80593888, 0.47144476]])

In [21]:
# standard normal distribution
np.random.randn(3,2)

array([[-1.10987537, -0.94368938],
       [ 0.21273838,  0.57911866],
       [-2.49487872,  1.62482042]])

In [22]:
C = np.array([1,2,3,4,5])
np.sum(C)

15

In [23]:
np.mean(C)

3.0

In [24]:
np.std(C)

1.4142135623730951

In [25]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
np.mean(B, axis=0)

array([3., 4.])

In [27]:
np.mean(B, axis=1)

array([1.5, 3.5, 5.5])